# Generated by Django 4.2.5 on 2023-09-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('docs', models.TextField()),
                ('status', models.CharField(choices=[('bajarildi', 'Bajarildi'), ('bajarilmadi', 'Bajarilmadi'), ('bajarilmoqda', 'Bajarilmoqda')], max_length=30)),
            ],
        ),
    ]
